# automatic testing with Travis CI!

language: javascript

node_js: v10

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn

script:
  - yarn test-site && yarn test-cli
